apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: elik
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: elik
    app.kubernetes.io/part-of: byoc-app-owyp
  name: elik
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: elik
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: elik
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-hbsy-tenant/byoc-app-owyp/elik@sha256:769dfe6fba9b670fbd529c20e56c5480f6448ebd29593ba9422e2005a9b1bd20
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
